### ISSUE TITLE
Improve the labels/states of the loans and information shown

### ISSUE THREAD

**Issue by sirsoth** [ETHLend/Baiji-public#49] opened 2018-12-29 13:39 UTC
We would need to improve if possible the labels/states of the loans to make them more easy to understand, for example if we have a request in "waiting for lender" the counterpart state in a loan offer should be "waiting for borrower" and not "waiting for collateral" this way users could understand better.

Also we could check the platform messages to check if in loan offers and requests the way to display the information its "similar"

**Comment by The-3D** [comment] 2018-12-30 20:55
It's already like this, i don't see honestly were the issue is. The "waiting for collateral" state is only for bitcoin loan requests, where the procedure is reversed as the lender has to place the funds first, thus the loan goes in "waiting for collateral". Of course we are going to add a info message in case of BTC loans to further explain this, there is already a issue opened for that. I'm closing this, if there is anything else that is unclear please comment here and i will try to explain

**Closed as completed by The-3D** 2018-12-30 20:55 UTC
Labels: enhancement
