### ISSUE TITLE
[bug] No loan information displayed when clicking an already funded or completed loan

### ISSUE THREAD

**Issue by helpfulBrother** [ETHLend/Baiji-public#60] opened 2019-01-04 08:00 UTC
Here is what I see

![image](https://user-images.githubusercontent.com/44999712/50678481-98e0bb80-104a-11e9-890c-0167691aaece.png)

**Comment by The-3D** [comment] 2019-01-04 09:36
this is duplicate of #33, closing

**Closed as completed by The-3D** 2019-01-04 09:36 UTC
