### ISSUE TITLE
[bug] Loan not displayed under 'My Loans' after creation (BTC as collateral)

### ISSUE THREAD

**Issue by helpfulBro** [ETHLend/Baiji-public#11] opened 2018-11-14 11:33 UTC
TX : https://kovan.etherscan.io/tx/0x6157d5e8253968745c582f2f616f2da2deffdb3546bf5dd6c6e1d818525d31ef

I can see it in the all requests view though.

**Comment by helpfulBro** [comment] 2018-11-14 11:49
Here is a loan that I funded - not showing either.

TX : https://kovan.etherscan.io/tx/0xbafe32314dd4d74ad8ff5a8d7049a18669dc7a3ab41ab33ff1936e54c6997a60

**Comment by The-3D** [comment] 2018-12-05 09:47
the bitcoin oracle was down at that time, that causes the loan not being registered. Closing this as it's not a bug itself, but we will improve the error handling in the case of the oracle being down.

**Closed by The-3D** 2018-12-05 09:47 UTC
